// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATLswiP8FJoel4pO-ODjHSb_cOTWmFco',
    appId: '1:737189169317:android:957a9503971641c055e54c',
    messagingSenderId: '737189169317',
    projectId: 'contacts-c5955',
    storageBucket: 'contacts-c5955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD650yjnvTKB5qBMNmMVpH8YlJZlpqJwmM',
    appId: '1:737189169317:ios:cf19d17ec0d4e33755e54c',
    messagingSenderId: '737189169317',
    projectId: 'contacts-c5955',
    storageBucket: 'contacts-c5955.appspot.com',
    iosClientId: '737189169317-svhl48o0drm67vdsiof2d2nd7ic0ah5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );
}
